// Navigation
export const SET_CURRENT_CONTENT = 'SET_CURRENT_CONTENT';

// Stops
export const REQUEST_STOPS = 'REQUEST_STOPS';
export const RECEIVE_STOPS = 'RECEIVE_STOPS';
export const RECEIVE_STOPS_CLEAR = 'RECEIVE_STOPS_CLEAR';
export const CLEAR_STOPS = 'CLEAR_STOPS';
export const SET_ADDRESS = 'SET_ADDRESS';
export const FIND_CURRENT_LOCATION = 'C.FIND_CURRENT_LOCATION';
export const SET_LOCATION = 'SET_LOCATION';
export const SAVE_SCROLL = 'SAVE_SCROLL';

// Departures
export const REQUEST_DEPARTURES = 'REQUEST_DEPARTURES';
export const RECEIVE_DEPARTURES = 'RECEIVE_DEPARTURES';
export const LEAVE_DEPARTURES_VIEW = 'LEAVE_DEPARTURES_VIEW';
