// Navigation
export const SET_CURRENT_CONTENT = 'SET_CURRENT_CONTENT';
export const SAVE_SCROLL = 'SAVE_SCROLL';

// Stops
export const REQUEST_STOPS = 'REQUEST_STOPS';
export const RECEIVE_STOPS = 'RECEIVE_STOPS';
export const RECEIVE_STOPS_CLEAR = 'RECEIVE_STOPS_CLEAR';
export const CLEAR_STOPS = 'CLEAR_STOPS';
export const SET_ADDRESS = 'SET_ADDRESS';
export const FIND_CURRENT_LOCATION = 'FIND_CURRENT_LOCATION';
export const SET_LOCATION = 'SET_LOCATION';
export const CLEAR_LOADING = 'CLEAR_LOADING';
export const FLAG_INITIAL_LOAD_DONE = 'FLAG_INITIAL_LOAD_DONE';

// Departures
export const REQUEST_DEPARTURES = 'REQUEST_DEPARTURES';
export const RECEIVE_DEPARTURES = 'RECEIVE_DEPARTURES';
export const LEAVE_DEPARTURES_VIEW = 'LEAVE_DEPARTURES_VIEW';

// Statuses
export const REQUEST_STATUSES = 'REQUEST_STATUSES';
export const RECEIVE_STATUSES = 'RECEIVE_STATUSES';
export const LEAVE_STATUSES_VIEW = 'LEAVE_STATUSES_VIEW';
