reporting:
    watermarks:
        statements: [55, 85]
        branches: [55, 85]
        functions: [55, 85]
        lines: [55, 85]
check:
    global:
        root: ./coverage
        statements: 85
        lines: 85
        branches: 85
        functions: 85
        excludes: []
