service: default
runtime: nodejs
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 60
skip_files:
  - ^(.*/)?\DS_Store$
  - ^(.*/)?\.md$
  - ^(.*/)?\.yml$
  - ^(.*/)?\.yaml$
  - ^.*\.git(/.*)?
  - ^.*node_modules(/.*)?
  - ^client(/.*)?
  - ^download(/.*)?
handlers:
  # redirect to ssl
  - url: /.*
    script: IGNORED
    secure: always
